[platformio]
default_envs = esp32s3_primary, esp32wrover_secondary

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:esp32s3_primary]
board = esp32-s3-devkitc-1
build_flags = 
    -D CORE_DEBUG_LEVEL=5
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> -<SensorShield.cpp>
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    madhephaestus/ESP32Servo@^1.1.1

[env:esp32wrover_secondary]
board = esp32-wrover-kit
lib_deps =
    ${env.lib_deps}
    bogde/HX711@^0.7.5
    teckel12/NewPing@^1.9.7
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.14